# Generated by Django 5.1.1 on 2024-09-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_firsname_member_firstname_member_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Factory', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('TeamID', models.CharField(max_length=50)),
                ('FullName', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('Act', models.IntegerField(null=True)),
                ('UserLevel', models.IntegerField(null=True)),
                ('LastUpdate', models.DateTimeField(null=True)),
            ],
        ),
    ]
